from pathlib import Path

if config.get("length_model"):
    include: "rules/subsample_model.smk"
else:
    include: "rules/subsample_random.smk"
include: "rules/create_mixes.smk"

rule all:
    input:
        expand(Path('{ROOT}') / '{mix_n}' / '{mix_n}.fq', ROOT=config['output_dir'], mix_n=config['mixes'].keys()),
        expand(Path('{ROOT}') / '{mix_n}' / 'ground_truth.names', ROOT=config['output_dir'], mix_n=config['mixes'].keys())
